[package]
name = "shader"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = {git = "https://github.com/Rust-GPU/rust-gpu.git"}
bytemuck = { version = "1.18.0", features = ["derive"] }

